[package]
name = "r"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
futures = "0.3.30"
wasm-bindgen = { version = "0.2.92", features = [] }
wasm-bindgen-futures = "0.4.42"
